# ============================================================
# ANSIBLE INVENTORY FILE (AUTO-GENERATED BY TERRAFORM)
# ============================================================
# DO NOT EDIT THIS FILE - edit terraform/templates/inventory.ini.tpl instead
# Then run: terraform apply
# ============================================================

[app_servers]
vm1 ansible_host=${app_server_ip} ansible_user=${ssh_user} ansible_ssh_private_key_file=${ssh_key_path}

[jenkins_servers]
vm2 ansible_host=${jenkins_server_ip} ansible_user=${ssh_user} ansible_ssh_private_key_file=${ssh_key_path}

[all:vars]
ansible_python_interpreter=/usr/bin/python3
