# ANSIBLE INVENTORY (AUTO-GENERATED BY TERRAFORM)
# Dit bestand wordt automatisch gegenereerd door Terraform.
# De IP adressen komen van de Elastic IPs.
#
# NIET HANDMATIG BEWERKEN! Wijzig in plaats daarvan:
#   terraform/templates/inventory.ini.tpl

[app_servers]
vm1 ansible_host=${app_server_ip} ansible_user=${ssh_user} ansible_ssh_private_key_file=~/.ssh/${ssh_key_name}.pem

[jenkins_servers]
vm2 ansible_host=${jenkins_server_ip} ansible_user=${ssh_user} ansible_ssh_private_key_file=~/.ssh/${ssh_key_name}.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
