// JENKINSFILE (AUTO-GENERATED BY TERRAFORM)
// Dit bestand wordt automatisch gegenereerd door Terraform.
// De APP_SERVER IP wordt ingevuld vanuit de Elastic IP.
//
// NIET HANDMATIG BEWERKEN! Wijzig in plaats daarvan:
//   terraform/templates/Jenkinsfile.tpl
//
// Na wijzigingen: terraform apply

pipeline {
    agent any

    environment {
        // Deze waardes worden automatisch ingevuld door Terraform
        APP_SERVER = '${app_server_ip}'
        APP_USER = '${ssh_user}'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Code ophalen van GitHub...'
                checkout scm
            }
        }

        stage('Pull Latest Code') {
            steps {
                echo "Laatste code ophalen op $${APP_SERVER}..."
                sshagent(['vm1-ssh-key']) {
                    sh """
                        ssh -o StrictHostKeyChecking=no $${APP_USER}@$${APP_SERVER} '
                            cd /opt/flask-app &&
                            git pull origin Test-Documentation
                        '
                    """
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Docker image bouwen op $${APP_SERVER}..."
                sshagent(['vm1-ssh-key']) {
                    sh """
                        ssh -o StrictHostKeyChecking=no $${APP_USER}@$${APP_SERVER} '
                            cd /opt/flask-app/flask-app &&
                            sudo docker build -t flask-app:latest . &&
                            sudo docker stop flask-app || true &&
                            sudo docker rm flask-app || true &&
                            sudo docker run -d --name flask-app --restart unless-stopped -p 80:80 flask-app:latest
                        '
                    """
                }
            }
        }

        stage('Health Check') {
            steps {
                echo 'Wachten tot container is opgestart...'
                sh 'sleep 10'
                echo 'Controleren of app draait...'
                sh "curl -f http://$${APP_SERVER}:80/health || exit 1"
            }
        }
    }

    post {
        success {
            echo 'Deployment geslaagd!'
            echo "App URL: http://$${APP_SERVER}"
        }
        failure {
            echo 'Deployment mislukt!'
        }
    }
}
