// ============================================================
// JENKINSFILE (AUTO-GENERATED BY TERRAFORM)
// ============================================================
//
// !!! DO NOT EDIT THIS FILE MANUALLY !!!
//
// This file is automatically generated by Terraform when you run:
//   terraform apply
//
// The APP_SERVER IP is filled in from Terraform's Elastic IP.
// If you need to change the pipeline logic, edit the TEMPLATE:
//   terraform/templates/Jenkinsfile.tpl
//
// After editing the template, run: terraform apply
// ============================================================

pipeline {
    agent any

    environment {
        // =========================================
        // CONFIGURATION (auto-filled by Terraform)
        // =========================================
        // These values come from Terraform template variables:
        //   app_server_ip  -> aws_eip.app_server.public_ip
        //   ssh_user       -> "admin" (Debian default)
        // =========================================
        APP_SERVER = '${app_server_ip}'
        APP_USER = '${ssh_user}'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Pulling code from GitHub...'
                checkout scm
            }
        }

        stage('Pull Latest Code') {
            steps {
                echo "Pulling latest code on $${env.APP_SERVER}..."
                sshagent(['vm1-ssh-key']) {
                    sh """
                        ssh -o StrictHostKeyChecking=no $${env.APP_USER}@$${env.APP_SERVER} '
                            cd /opt/flask-app &&
                            git pull origin main
                        '
                    """
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building Docker image on $${env.APP_SERVER}..."
                sshagent(['vm1-ssh-key']) {
                    sh """
                        ssh -o StrictHostKeyChecking=no $${env.APP_USER}@$${env.APP_SERVER} '
                            cd /opt/flask-app/flask-app &&
                            sudo docker build -t flask-app:latest . &&
                            sudo docker stop flask-app || true &&
                            sudo docker rm flask-app || true &&
                            sudo docker run -d --name flask-app --restart unless-stopped -p 80:80 flask-app:latest
                        '
                    """
                }
            }
        }

        stage('Health Check') {
            steps {
                echo 'Waiting for container to start...'
                sh 'sleep 10'
                echo 'Checking if app is running...'
                sh "curl -f http://$${env.APP_SERVER}:80/health || exit 1"
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
            echo "App URL: http://$${env.APP_SERVER}"
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
